### ISSUE TITLE
issue with update transactions

### ISSUE THREAD

**Issue by mohammad-aliB** [actualbudget/node-api#7]
when i run update transactions i get the following error:

```
  Error: [API Error] Tried to edit unknown transaction id: undefined
      at Promise.catch.err (/Users/mohammad/node_modules/@actual-app/api/connection.js:26:13)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
```

the code im using is as follows:
```
let api = require('@actual-app/api');
async function run() {
  let budget = await api.getAccounts();
  let f= await api.addTransactions('REDACTED',[{date:'2020-01-02'}])
  let e= await api.getTransactions('REDACTED','2020-01-01','2022-01-20');
  let g= await api.updateTransaction(e[e.length-1]["id"],{})
}
api.runWithBudget('My-Finances-b1bae9d', run);
```

other methods such as `api.deleteTransaction()` work fine so i know the id i am using is correct.

**Comment by culpeppers** [comment]
I am also receiving the same error, @jlongster
